install.packages(setdiff(c("shiny", "dplyr", "tidyr", "shinyBS"), installed.packages()))
library(shiny)
library(shinyBS)
library(tidyr)
library(dplyr)
library(Rcpp)
sourceCpp("simulations.cpp")
source("ui.r")
source("server.r")
InteractivedynaViTE <- shinyApp(ui, server) 
runApp(InteractivedynaViTE)
